
import { AuthProvider } from "@repo/ui/auth/AuthProvider"
import Navbar from "@repo/components/Navbar"
import Footer from "@repo/components/Footer"
import ThemeProvider from "@repo/system/ThemeProvider"

import type { Metadata } from "next";
import "./globals.css";
import { UserNavbar } from "./components/UserNavbar";
import {  UserCoinStatusIcon } from "./components/license/UserCoinStatus";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar actions={<UserNavbar />} userCoins={<UserCoinStatusIcon/>}/>
            <main className="bg-background">{children}</main>
            <Footer />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}